# -*- coding: utf-8 -*-
"""capCount

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z91EAyq9OGNwThbDel_2mCXijcqBN63H
"""

test_str = 'HelloTreeIlovePlant'

res = [idx for idx in range(len(test_str)) if test_str[idx].isupper()]
print( str(res))